stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: lakatostomi/demo-app
  IMAGE_TAG: demo-restapi-1.0

run_tests:
  stage: test
  image: maven:latest 
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
      mvn test

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  script:
    echo "Login to server!"
    echo "Login to dockerhub!"
    echo "Stop and remove running app on server!"
    echo "Run latest app on server!"