workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - test
  - build

variables:
  IMAGE_NAME: lakatostomi/myprojects
  IMAGE_TAG: cc-restapi-1.0

run_tests:
  stage: test
  image: maven:3.8.6-eclipse-temurin-17
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
      mvn test

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

---

#workflow:
#  rules:
#    - if: $CI_COMMIT_BRANCH == "main"
#
#stages:
#  - test
#  - build & push
#
#variables:
#  JSON_KEY: $KEY
#  ACCOUNT: $SA
#
#image: lakatostomi/maven-cloudsdk:latest
#
#test:
#  stage: test
#  script:
#    - mvn test
#
#build_push:
#  stage: build & push
#  before_script:
#    - gcloud auth activate-service-account $ACCOUNT --key-file=$JSON_KEY
#    - gcloud auth configure-docker eu.gcr.io
#  script:
#    - mvn clean install -DskipTests
