
services:
  server:
    image: ccapp:0.0.1-SNAPSHOT
    container_name: RESTAPI
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/$MYSQL_DB
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - test-network
    links:
      - mysqldb
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.30
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD",  "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 2
networks:
  test-network: